### ISSUE TITLE
Issue with configuration: "ERR_DATA_SIZE_NOT_MATCH"

### ISSUE THREAD

**Issue by facchetz** [xreef/LoRa_E32_Series_Library#15]
Ciao Renzo, I have a problem with the getModuleConfiguration function. I have a E32-868T30D connected to an ESP8266 (NodeMCU V3). I tried to upload the get configuration example
(https://www.mischianti.org/2019/10/29/lora-e32-device-for-arduino-esp32-or-esp8266-configuration-part-3/ the first example), I get the error "ERR_DATA_SIZE_NOT_MATCH" and an exception, next the microcontroller resets. The E32 works well with your library and the sendMessage and readString functions but I can't read the configuration... I also tried with the EBYTE configuration software and an Arduino UNO with a level converter for TX and RX pins and it works... What I have to do?
Grazie mille!

**Comment by xreef** [comment]
I had some problem with 868, seems that have an Internal resiator on rx tx, first try to remove the pull up reaistor than if works try to raise the pull up resistor to a good value.
But first add an external power supply.
Bye Renzo
