### ISSUE TITLE
Error: Data size not match!

### ISSUE THREAD

**Issue by masc-it** [xreef/LoRa_E32_Series_Library#18]
I'm trying to send a simple broadcast message from my heltec lora v2 esp32 to my arduino mega, but I receive **Data size not match!** as response.
If I use the same exact code on my arduino mega, it returns **success** just fine.

```
void sendMsg(){
  Serial.println("Broadcast message");

  ResponseStatus rs = e32ttl.sendBroadcastFixedMessage(0x06, "hello");
	Serial.println(rs.getResponseDescription());

}
```

Any clue about this behaviour? @xreef

**Comment by xreef** [comment]
Hi onipot,
It's a strange behaivor, can you send me the configuration of esp32 and Mega?
If you attach the file to do the test It's better, use the forum for this.
Thanks Renzo
