### ISSUE TITLE
RAM memory saturation

### ISSUE THREAD

**Issue by AB-informatica-service** [xreef/LoRa_E32_Series_Library#19]
I noticed that every time a message is transmitted the RAM memory is filled and it is never deallocated causing the filling and the consequent reset of the ATMEGA328P.

**Comment by xreef** [comment]
Thanks for the issue, I fixed It.
Pay attention on use string message without size, if there are more message on buffer receiveMessage read all messge in the busser use receiveMessageUntil to read one to one.
Bye Renzo
