### ISSUE TITLE
Re-transmitting issues (fixed communication)

### ISSUE THREAD

**Issue by masc-it** [xreef/LoRa_E32_Series_Library#22]
@xreef I have problems with this pipeline:

1) Arduino 1:
- sendFixedMessage(0,3,6, "test");

2) Arduino 2:
- receiveMessage() 
- sendResponseStruct()

3) Arduino 1:
- readResponseStruct()

Only the first time everything's fine.
From the 2nd iteration receiveMessage() (step 2) returns garbage, something like: @@test1.

Doing some testing I have found out that the garbage disappears if I do not call sendResponseStruct() (step 2)

**Comment by xreef** [comment]
Hi onipot,
It's difficult to debug with this informations, i think you must send the code, you can use the site forum.
Bye Renzo
