### ISSUE TITLE
How do I know if the ebyte e32 ttl100 module is broken?

### ISSUE THREAD

**Issue by aliustunelin** [xreef/LoRa_E32_Series_Library#23]
hello Renzo,
First of all thank you very much for writing the library, I used it many times.

but now I have a problem: i connected the arduino mega and the e32 board without a pull-up resistor in between 
Especially  m1 m0 rx tx pins and after that I could not communicate,
As far as I know the card should work like this, I remember it was a recommended use in the datasheet.
How can I tell if the card is burned now?
using a network analyzer, for example
Or is there a library that checks that the uart connection is working properly?

or i hope you know better

**Comment by xreef** [comment]
Hi, When I have a problem with e32 first I try to do a reset from the library, than I try with the official Ebyte software, than I use a logic analizer and check if data are transmitted to the serial and AUX pin change status.

Logic analizer is inexpensive but very  important to debug serial i2c or spi.

https://s.click.aliexpress.com/e/_AOKRJn

Bye Renzo
