### ISSUE TITLE
Computer issue related to this library

### ISSUE THREAD

**Issue by jtupulis** [xreef/LoRa_E32_Series_Library#24]
Hi,

It might or might not be related, but please look at [my post](https://forum.arduino.cc/index.php?topic=719357.0) on Arduino forums. I'm just hoping you have seen anything similar.

Veiksmi,
Jānis

**Comment by xreef** [comment]
The super efficient @per1234 give you a response on forum.
Bye Renzo

**Comment by jtupulis** [comment]
My stupid mistake, sorry for bothering!
