### ISSUE TITLE
How to monitor TX_RX quality in E32

### ISSUE THREAD

**Issue by DedePele** [xreef/LoRa_E32_Series_Library#26]
Hi, 

Please let me know if there is some way to check transmission Quality in E32 because I think they have no RSSI or  SRN...

Thank you

**Comment by xreef** [comment]
Hi DedePele,
no e32 can't do that, of you need RSSI, repeater function, big packet size and other you can try e22.
The library is similar, but support this features.
https://www.mischianti.org/category/my-libraries/ebyte-lora-e22-devices/
Bye Renzo
