### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by clabnet** [xreef/LoRa_E32_Series_Library#28]
Are these typo errors ?

...
We can use directly a **SoftwareSerial** with another constructor

LoRa_E32(**HardwareSerial*** serial, UART_BPS_RATE bpsRate = UART_BPS_RATE_9600);
LoRa_E32(**HardwareSerial*** serial, byte auxPin, UART_BPS_RATE bpsRate = UART_BPS_RATE_9600);
LoRa_E32(**HardwareSerial*** serial, byte auxPin, byte m0Pin, byte m1Pin, UART_BPS_RATE bpsRate = UART_BPS_RATE_9600);
...

The last set of constructor is to permit to use an **HardwareSerial** instead of SoftwareSerial.

LoRa_E32(**SoftwareSerial*** serial, UART_BPS_RATE bpsRate = UART_BPS_RATE_9600);
LoRa_E32(**SoftwareSerial*** serial, byte auxPin, UART_BPS_RATE bpsRate = UART_BPS_RATE_9600);
LoRa_E32(**SoftwareSerial*** serial, byte auxPin, byte m0Pin, byte m1Pin

**Comment by xreef** [comment]
Hi,
I answered here https://www.mischianti.org/forums/topic/ebyte-e32-868t30d-reboot-loop
