### ISSUE TITLE
how to send data more than 58 bytes?

### ISSUE THREAD

**Issue by fixajteknik** [xreef/LoRa_E32_Series_Library#31]
![Adsız](https://user-images.githubusercontent.com/73440569/129515270-6c856e2f-55c8-45e8-9857-a5ed0071b8ac.jpg)

there are a restriction on library for up to 58 bytes. 

`#define MAX_SIZE_TX_PACKET 58`

even if I increase the 58 to for example 200 it doest send data. well there is no problem, transmitter says "succes" seen while compile but data not sending correctly. I have seen "ovf" or like that on serial monitor of receiver.

**Comment by xreef** [comment]
Hi,
the device can't send more of 58byte, tobaend more you must send more packets.
Bye Renzo
