### ISSUE TITLE
Could this library be useful for SPI operation of  a XBee radio module with Arduino?

### ISSUE THREAD

**Issue by ahmetakman** [xreef/LoRa_E32_Series_Library#32]
Hi everyone,
I have been trying to program my ESP32  with Arduino ide to communicate with XBee Pro S2C module on the SPI bus. I am aware this panel is not about XBee modules but, I am unable to find any useful information achieve communicate them. There is no example code for this operation as well. Since the LoRa modules also use the SPI bus to communicate, could this library be useful for the SPI operation of the XBee radio module with Arduino IDE? 
Thanks

**Comment by xreef** [comment]
Hi  ahmetakman,
no sorry, only UART device.
Bye Renzo
