### ISSUE TITLE
encryption ?

### ISSUE THREAD

**Issue by cryptolok** [xreef/LoRa_E32_Series_Library#35]
hi,
first of all, thank you for the work that allows people to simplify the things ^^
I was just wandering, what's the purpose of the [encryption](https://github.com/xreef/LoRa_E32_Series_Library/blob/c7e40a8e36aaca58aac26d94acf84909844aeb3f/LoRa_E32.cpp#L874) function ?
as far as I can see, this part of code it never used and the data is sent in clear to the device, I know the E32 user manual specifies encryption and compression, so that would mean that it's hardware-based, not software
although, the KeeLoq algorithm is not a rare thing for IoT, I still would like to know the choice of the key :)
thanks

**Comment by xreef** [comment]
Hi, cryptolok,
Yes, the encryption is hardware-based, but if you use a broadcast and somebody listens to the message, he can read the news with another e32.
In my mind, I started to think about additional encrypting for the message, but I never developed and documented it.
Bye Renzo
