### ISSUE TITLE
broken table in README.md

### ISSUE THREAD

**Issue by ratio-x** [xreef/LoRa_E32_Series_Library#39]
In section "SPED detail" there is a broken table "UART Parity bit"

UART mode can be different between communication parties |7|6|UART parity bit|Const value| |---|---|---|---|---| |0|0|8N1 (default)|MODE_00_8N1| |0|1|8O1|MODE_01_8O1| |1|0|8 E1|MODE_10_8E1| |1|1|8N1 (equal to 00)|MODE_11_8N1|

**Comment by xreef** [comment]
Thanks ratio-x,
I'm going to fix it, but It's better if you read directly the original document, GitHub version I think It's not updated.
https://www.mischianti.org/2019/10/21/lora-e32-device-for-arduino-esp32-or-esp8266-library-part-2/
Bye Renzo
