### ISSUE TITLE
Stm32 with LoRa E32 library

### ISSUE THREAD

**Issue by fixajteknik** [xreef/LoRa_E32_Series_Library#42]
Hi, master, 
Well you have test e32 lora modules with arduino, esp modules very thanks for you. Do you have a plan also making test for STM32 nucleo series. There too much demand for stm32 series. But i didnt see any library for that.

**Comment by xreef** [comment]
Hi @fixajteknik ,
I start the tutorial on stm32, and I already test and develop the ftp server for stm32 and the ssl implementation of ethernet to send email with Gmail.
Now i finished the article about sd and spi flash always for stm32.

And i start the support and shield of Ebyte LoRa for stm32.

But I use blue pill and black pill.

I hope to start publish all soon, but I already write more then 50 articles and I don't know when the stm32 will be released.

If you are interested in something in particular write to the forum so we discuss about the roadmap.

Bye Renzo
