### ISSUE TITLE
Raspberry Pi Pico with LoRa E32 library

### ISSUE THREAD

**Issue by janczeresnia** [xreef/LoRa_E32_Series_Library#43]
Hi
You wrote a very nice library. Is there support for Raspberry Pi Pico microcontroller? And if so, how to configure it?
Library works great with Seed Studio XIAO and ESP8266 D1 but not with Raspberry Pi Pico :(

**Comment by xreef** [comment]
Hi @janczeresnia,
I'll start work on Pi Pico and STM32 in the next few days. 
I'm going also to create new shields for that devices.

Bye Renzo

**Comment by janczeresnia** [comment]
Thank you for the quick reply. Regards.

**Comment by xreef** [comment]
I reopen this issue, and I close It when development will be effective, so I alert you.
Bye Renzo

**Comment by RootInit** [comment]
Any update on this?

**Comment by xreef** [comment]
Hi,
I must test it, I think probably it work, but not yet tested.
If I find some time I test it in the next week.
Bye Renzo

**Comment by xreef** [comment]
Hi all,
I tested the Raspberry Pi Pico and It's fully supported.

You can find here the configuration and wiring diagram.

https://www.mischianti.org/forums/topic/ebyte-lora-uart-arduino-library-raspberry-pi-pico-support/

Bye Renzo

**Comment by RootInit** [comment]
Tysm!
