### ISSUE TITLE
Best way for connecting 100 loras together?

### ISSUE THREAD

**Issue by fixajteknik** [xreef/LoRa_E32_Series_Library#44]
Hi renzo we need your help, a my customer asking me, assume that there 100 cars on a area (about 4km2) we want collect GPS datas of all cars with LoRa in a one center . Which is the best and fast way? If we use ask one node than listen it, it goes so many delay time. How can we achieve simultaneously. Because lora hase 512 bytes buffer (e22 has 1000) our packed size about 30 bytes. In logical i should get some many loras datas in same time. But in reality after receiving one data from first lora, recever lora deleting its buffer. We cant find a good way please help us?

**Comment by xreef** [comment]
Hi @fixajteknik,
(sorry for the late response but finally, I'm returned home)
I think the best way is to use a small packet and create a gateway without latency, a device that read all messages in the buffer (as soon as possible), with one or multiple receiver devices, and sends It to a push server (like MQTT) that send the packet to without latency.
Similar to the gateway project described here.
https://www.mischianti.org/2021/07/20/ebyte-lora-e32-gateway-manage-via-rest-and-websocket-esp8266-esp32-1/
If you need more help use the forum, I read It more than other channels.
Bye Renzo
