### ISSUE TITLE
Can you change LoRa PHY parameters like Spreading Factor (sf), Bandwidth, coding rate etc. ?

### ISSUE THREAD

**Issue by aryangupta0405** [xreef/LoRa_E32_Series_Library#45]
Very well-written library, but I wanted to ask - is it possible to change the PHY setting using this library of the E32 modules?

**Comment by xreef** [comment]
Hi,
you can find all information about that in [this article](https://www.mischianti.org/2019/10/21/lora-e32-device-for-arduino-esp32-or-esp8266-library-part-2/).

Bye Renzo
