### ISSUE TITLE
How to configuration set long distance...?

### ISSUE THREAD

**Issue by cattHoons** [xreef/LoRa_E32_Series_Library#49]
![image](https://user-images.githubusercontent.com/55969706/199677734-5d8275f9-ef6a-468a-b7a0-4bf9d0e778f4.png)

I tried changing the air data rate setting, but the 1:1 communication distance from the outside is less than 10~15m,
and communication is not possible over the 15m distance.

If i set the transmission cycle to 7 seconds, it sometimes takes 10 to 15 seconds to receive within 15 meters.
What should I do?

**Comment by cattHoons** [comment]
+) i use ES32-900T30D

**Comment by xreef** [comment]
Hi,
sorry I lost this message, but to get a good distance you need a good amperage and a big antenna.
https://www.mischianti.org/forums/topic/e22-distance-test/
Bye Renzo
