### ISSUE TITLE
Can OPERATING_FREQUENCY support 923Mhz band? 

### ISSUE THREAD

**Issue by zachary-y-negawatt** [xreef/LoRa_E32_Series_Library#52]
For my country, the legal LoRa band is 920 – 925 MHz. So I would like to know if it is possible to change the `statesNaming.h` to support 923Mhz.

**Comment by xreef** [comment]
Hi,
you can use E32-900T20D model that support from 862 to 931MHz.
Bye Renzo

**Comment by zachary-y-negawatt** [comment]
Oh, Thank you so much.
I bought the hardware right now. But how can I set up the right channel configure for the program?

**Comment by xreef** [comment]
Hi,
you can set the channel and read the console output on configuration read.
Bye Renzo
