### ISSUE TITLE
Sending a byte array

### ISSUE THREAD

**Issue by TheSnowFall** [xreef/LoRa_E32_Series_Library#54]
Hello @xreef ,
I am happy you worked on such an excellent library. 
According to my inspection, you are sending string data through transmission. But I do not want to send any strings. I want to send a hex or bin directly. 
How to send it without saving the byte array data in string format?
Let me know, please.

**Comment by xreef** [comment]
Hi,
you can use a structure as described [here](https://mischianti.org/2019/12/03/lora-e32-device-for-arduino-esp32-or-esp8266-power-saving-and-sending-structured-data-part-5/), or instead of structure pass the specified bytearray.
Bye Renzo
