### ISSUE TITLE
Can I just do simple Serial. write without this library ? 

### ISSUE THREAD

**Issue by SurenBono** [xreef/LoRa_E32_Series_Library#57]
example transmission code :

char a [ ]="tx1 , transmit test ,123 , noise check ,”;
Serial.write(a, sizeof(a)-1);

example reception code :

char rawData[64]=" ";
size_t byteCount = rx.readBytesUntil('\n', rawData, sizeof(rawData) - 1); //read in data to buffer
rawData[byteCount] = NULL;
Serial.println(rawData);

//As simple as a hc12 module

I want to score on this module for GPS RCC ( radio controlled clock) broadcast experiment... so schools, hospital, factory, government offices, train/ bus stations,the masses... etc.. gets redundancy & accurate GPS timekeeping.. 

https://github.com/SurenBono/RadioFrequency/tree/main/HC-12/GPS_HC12_toMany_v10_MEGA

**Comment by xreef** [comment]
Hi,
yes you can, but you can use only transparent transmission or manage addressing ecc. and you must do all the configuration with the library or in manual mode.
Bye Renzo

**Comment by SurenBono** [comment]
Hi thank you for your reply... you mean I set the parameters with the .exe
and only use SoftwareSerial. h while it does the magic..

**Comment by xreef** [comment]
For transparent transmission, yes, but you must pay attention to not sending new data before finishing the previous send and checking the packet size.
Bye Renzo

**Comment by SurenBono** [comment]
.. of course... I will use if data available to send function ..

void transmitData() {
if(Serial2.availableForWrite()){
Serial2.write(TX,sizeof(TX)-1);}
