### ISSUE TITLE
is it compatible with E32 433T20D module? 

### ISSUE THREAD

**Issue by SurenBono** [xreef/LoRa_E32_Series_Library#58]
I need to set it to broadcast address 0xFFFF on channel 0x0004 for the transmission as the datasheet specified and all other reception on their own address but on the same channel 0x0004.. and it supposed to receive the msg at the same time... GPS RCC Experimental 20dBm 
example transmit data = " dd. mm. yy, weekday, AM 12:00,U+8,";  transparent non encrypted.. it's just timekeeping data.. 

https://github.com/SurenBono/RadioFrequency/tree/main/HC-12/GPS_HC12_toMany_v10_MEGA

:)

**Comment by xreef** [comment]
Hi,
the EByte module wraps the message and encrypts It (some people decrypt It; there is something in the forum).
You can follow the tutorial to manage the broadcast and monitor the environment.
Bye Renzo

**Comment by SurenBono** [comment]
... nobody in 300 km radius of my residency cares or know about any e32
spying/decoding stray rf in my area ... it's ok if the could see it anyway
(transparent)it's just a clock signal broadcast experiment similar to a
dcf77 radio controlled clock.. I tried a simpler module like a hc12.. but
the module broke down..
