### ISSUE TITLE
RSSI for Ebyte E32

### ISSUE THREAD

**Issue by DARXS** [xreef/LoRa_E32_Series_Library#59]
Hi xreef,
Is it possible to calculate the RSSI of the ebyte E32?
And if the module does not allow it due to hardware, is it possible to calculate the RSSI via software?

**Comment by xreef** [comment]
Hi darxs,
E32 not offer the possibility to manage the RSSI, and I think that isn't possible to manually calculate it.
Bye Renzo

**Comment by DARXS** [comment]
Is it possible to purchase SNR instead of RSSI?
