### ISSUE TITLE
Receiver power in real time with Ebyte E32 900T30D

### ISSUE THREAD

**Issue by DARXS** [xreef/LoRa_E32_Series_Library#60]
Hi xreef

I have ebyte e32 900t30d LoRa modules and I would like to know how to acquire the receiver power in real time at certain distances and if it is possible to acquire the path loss exponent?

**Comment by xreef** [comment]
Hi DARKS,
the e32 module does not support the RSSI, so I think that you can't get the signal strength.
Bye Renzo
