### ISSUE TITLE
LoraWan example

### ISSUE THREAD

**Issue by Kevinvincentals** [xreef/LoRa_E32_Series_Library#62]
Hi.
Is there any plan to integrate some kind of LoraWan example to use it with like TTN?

**Comment by xreef** [comment]
Hi kevin,
I'm not so happy to integrate a payment service, in the future probably I create a complete example with mqtt for network integration.
Bye Renzo

**Comment by Kevinvincentals** [comment]
Thanks for letting me know.
Could also be very useable in a private lorawan server. But Thanks!
