### ISSUE TITLE
ESP32 WROOM

### ISSUE THREAD

**Issue by JayZeeM** [xreef/LoRa_E32_Series_Library#63]
Hello my ESP32 WROOM doesnt have tx2 and rx2 can I use the tx0 and rx0? what will be the changes in the code

**Comment by JayZeeM** [comment]
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x40085ccf  PS      : 0x00060830  A0      : 0x800d1b09  A1      : 0x3ffc5160  
A2      : 0x3ffc5186  A3      : 0x00000000  A4      : 0x00000006  A5      : 0x3ffc5186  
A6      : 0x00002580  A7      : 0x0800001c  A8      : 0x00000009  A9      : 0x00000000  
A10     : 0x00000000  A11     : 0x00000003  A12     : 0x00000001  A13     : 0x000000ff  
A14     : 0x000000ff  A15     : 0x00000000  SAR     : 0x0000000a  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400840d1  LEND    : 0x400840d9  LCOUNT  : 0x00000027  


Backtrace: 0x40085ccc:0x3ffc5160 0x400d1b06:0x3ffc5170 0x400d32ee:0x3ffc51d0
ELF file SHA256: 5aeb3bbaffe4028b

Rebooting...

I am getting this output

**Comment by lovefool** [comment]
I don't know how to use TX0/RX0. For my project of E220, I modified H file (Lora_E220.h) to use espSoftwareSerial on ESP32.

**Comment by xreef** [comment]
Hi Jay,
you can find all Constructor possibilities [here](https://mischianti.org/ebyte-lora-e220-llcc68-device-for-arduino-esp32-or-esp8266-library-2/#Constructor).
You can pass the HardwareSerial you select as the first parameter.
Bye Renzo

**Comment by JayZeeM** [comment]
Hello. I used &Serial and when I get the configuration it shows success. Does that mean that the connections are ok? But when I'm trying to send a message using the sendreceiveTransparentMessage it cannot transmit.
