### ISSUE TITLE
Corrupted message

### ISSUE THREAD

**Issue by cRaZy92** [xreef/LoRa_E32_Series_Library#64]
Hello,
I have an issue for a pretty long time now, I have tried so many things so creating an issue on github is probably my last resort.

I have Arduino Uno (also tried with ESP8266 and ESP32) and Arduino Mega, They are set to exactly the same configuration.

This is the config from Arduino Mega with the corrupted message from the node:
![image](https://github.com/xreef/LoRa_E32_Series_Library/assets/33964772/27758090-1bbd-41b0-a29d-9b37b8951442)

This is the config from Arduino Uno with the correct message from the Arduino Mega:
![image](https://github.com/xreef/LoRa_E32_Series_Library/assets/33964772/21618bc5-1837-4476-bdbd-d508d1c401ef)

I don't know what else to provide since everything else works nicely, it's just that the message is partially corrupted.
Please let me know if there is something else that I can provide.

Thank you!

Edit: 
So I found out that the issue has something to do with the FastLED library since when I initialize LEDs on the Arduino Mega, the messages received are corrupted, I tried initializing LEDs on totally different pins that don't have LEDs connected, and still does the corrupted messages, so I am kind of weirded out by this

**Comment by xreef** [comment]
thanks for the feedback.
