### ISSUE TITLE
No Support for 5W E32 module

### ISSUE THREAD

**Issue by Maazulhaq5872** [xreef/LoRa_E32_Series_Library#66]
I am using two ebyte E32 433T37S, which is a 5W module, Whenever i try to use any kind of transmission from the library, i don't recieve anything on the other side. I also checked my wirings multiple times, + also added pull up and voltage divider on rx tx.
When I try to get configuration, i receieve "No response from the module, check wiring".
I also tried to use usb to ttl converter to configure thorugh rf setting software, but it also said model not supported.
I Purchased these through links provided in official website. This is not an invidual project but a  team project,, so any kind of help would be appreciated which allow me to do transmission and configure these module.

**Comment by xreef** [comment]
Hi,
the 5w module is supported; probably, you have a power supply issue.
Bye Renzo
