### ISSUE TITLE
'POWER_30' was not declared in this scope

### ISSUE THREAD

**Issue by d100cent** [xreef/LoRa_E32_Series_Library#9]
Even after #define E32_TTL_1W, staus showing 'POWER_30' was not declared in this scope error.

Kindly help ASAP.

**Comment by xreef** [comment]
Hi,
you can find a working example here
https://github.com/xreef/LoRa_E32_Series_Library/blob/master/examples/sendReceiveTransparentTransmissionE32_TTL_1W/sendReceiveTransparentTransmissionE32_TTL_1W.ino

Bye Renzo
